- hosts: shivan.xyz
  gather_facts: no
  become: True
  roles:
          - role: 'deploy/common/'
            name: Common tasks

          - role: 'deploy/tubestats-app'
            name: Deploy Tubestats application
            vars: 
                app_name: tubestats
                repo_link: https://github.com/shivans93/tubestats
                tubestats_port: 8999
                letsencrypt_email: shivan.sivakumaran@gmail.com

          - role: 'deploy/optomcalc-app'
            name: Deploy OptomCalc application
            vars: 
                app_name: optomcalc
                repo_link: https://github.com/shivans93/optomcalc
                app_port: 8000
                letsencrypt_email: shivan.sivakumaran@gmail.com
