- hosts: shivan.xyz
  gather_facts: no
  become: True
  roles:
          - role: 'deploy/common/update_server'
            name: Update server packages
            apt:
                    upgrade: dist
                    update_cache: yes

          - role: 'deploy/tubestats-app'
            name: Deploy Tubestats application
            vars: 
                tubestats_port: 8999
                domain_name: tubestats.shivan.xyz
                letsencrypt_email: shivan.sivakumaran@gmail.com
                user_name: shivan
