---
# FIXME: stuck on 'Please wait...'
- name: Create tubestats directory
  file:
          path: /home/{{ user_name }}/tubestats
          state: directory

- name: Git pull/clone tubestats repo
  ansible.builtin.git:
          repo: https://github.com/shivans93/tubestats
          dest: /home/{{ user_name}}/tubestats
          single_branch: yes
          version: main
          update: yes
 
- name: Copy .env file for tubestates app
  ansible.builtin.copy:
          src: .env
          dest: /home/{{ user_name }}/tubestats/.env
          owner: '{{ user_name }}'
          group: '{{ user_name }}'
          mode: '0644'

- name: Build docker image and run
  shell: >
         cd /home/{{ user_name }}/tubestats &&
         docker build -t tubestats:latest . &&
         nohup docker run -p 8999:8999/tcp --rm tubestats:latest &
 
