---
#
# Setting up nginx and certbot 
#
- name: Installing nginx for tubestats
  apt:
          name: nginx
          state: present

- name: Copy tubestats.shivan.xyz
  template:
          src: tubestats.shivan.xyz
          dest: /etc/nginx/sites-available/

- name: Activate the tubestats.shivan.xyz site
  file:
          src: /etc/nginx/sites-available/tubestats.shivan.xyz
          dest: /etc/nginx/sites-enabled/tubestats.shivan.xyz
          state: link

- name: Installing certbot using snap
  shell: "snap install --classic certbot"

- name: Preparing certbot
  file:
   src: /snap/bin/certbot
   dest: /usr/bin/certbot
   state: link

- name: Generate certs
  shell: >
          certbot --nginx --email '{{ letsencrypt_email }}'
          --non-interactive --agree-tos
          -d '{{ domain_name }}'

- name: Restart nginx.service
  systemd:
          state: restarted 
          name: nginx 

#
# Setting up project
# FIXME: Stuck on 'Please wait...'
#
- name: Create tubestats directory
  file:
          path: /home/{{ user_name }}/tubestats
          state: directory

- name: Git pull/clone tubestats repo
  ansible.builtin.git:
          repo: https://github.com/shivans93/tubestats
          dest: /home/{{ user_name}}/tubestats
          single_branch: yes
          version: main
          update: yes
 
- name: Copy .env file for tubestates app
  ansible.builtin.copy:
          src: .env
          dest: /home/{{ user_name }}/tubestats/.env
          owner: '{{ user_name }}'
          group: '{{ user_name }}'
          mode: '0644'

- name: Build docker image and run
  shell: >
         cd /home/{{ user_name }}/tubestats &&
         docker build -t tubestats:latest . &&
         nohup docker run -p 8999:8999/tcp --rm tubestats:latest &
 
